eureka:
  client:
    serviceUrl:
      # 在注册中心注册
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: Proxy
server:
  port: 8083
zuul:
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  routes:
      user-buy:
        service-id: micro-service-buy
        path: /buy/**
        stripPrefix: false
      user-sell:
        service-id: micro-service-sell
        path: /sell/**
        stripPrefix: false
  servlet-path: /