eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: Proxy
server:
  port: 8083
zuul:
  routes:
    MicroServiceBuy: /service/buy/**
    MicroServiceSell: /service/sell/**

