server:
  port: 9002

spring:
  application:
    name: service-redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    appname: service-redis