server:
  port: 8763

spring:
  application:
    name: service-ribbon-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    appname: service-ribbon-client
    lease-renewal-interval-in-seconds: 1